export enum Paths {
    HOME = '/',
    SIGN_UP = '/sign-up',
    SIGN_IN = '/sign-in',
    PROFILE = '/profile',
    SELECT_ROLE = '/select-role',
    TEST = '/test',
    FORGOTTEN_PASSWORD = '/forgotten_password',
    RESET_PASSWORD = '/reset_password/*',
    JOB_PAGE = '/job',
    SETTING_PAGE = '/setting',
    SEND_PROPOSAL = '/send_proposal',
    CONTACT_INFO = '/contact_info',
    JOBS = '/jobs',
    OFFERS = '/offers',
    CHAT = '/chat',
    SETTING_ID = '/setting/:id',
    CREATE_JOB_PAGE = '/createJob',
    TALENT = '/talents',
}
