export const contacts = [
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 1,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 2,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 3,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 4,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 5,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 6,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 7,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 8,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 9,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTA78Na63ws7B7EAWYgTr9BxhX_Z8oLa1nvOA&usqp=CAU',
        id: 10,
        name: 'Ali',
        project: 'Create UI Chat',
        active: false,
        isOnline: false,
    },
];
